university/app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('teachers/', views.teachers, name='teachers'),
    path('groups/', views.groups, name='groups'),
    path('departments/', views.departments, name='departments'),
    path('performance/', views.performance, name='performance'),
    path('students/', views.students, name='students'),
    path('subjects/', views.subjects, name='subjects'),
    path('add_subjects_mark/', views.add_subject_mark, name='add_subject_mark'),
    path('input_subject_id/', views.input_subject_id, name='input_subject_id'),
    path('upd_subjects_mark/<int:subject_id>/', views.update_subject_mark, name='update_subject_mark'),
    path('search_personal_info/', views.search_personal_info, name='search_personal_info'),
    path('login/', views.entrance, name='login'),
    path('login_dec/', views.login_dec, name='login_decv'),
    path('add_personal_info/', views.add_personal_info, name='add_personal_info'),
    path('add_teacher/', views.add_teacher, name='add_teacher'),
    path('add_subject/', views.add_subject, name='add_subject'),
    path('add_group/', views.add_group, name='add_group'),
    path('group_list/', views.group_list, name='group_list'),
    path('personal_info_list/', views.personal_info_list, name='personal_info_list'),
    path('login_dec/', views.login_dec, name='login_dec'),
    path('dean/', views.dean, name='dean'),
    path('personal_performance/', views.personal_performance, name='personal_performance'),
]

university/university/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

university/app/models.py
from django.db import models


class Parents(models.Model):
    id = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=255)
    Phone_number = models.CharField(max_length=255)

    class Meta:
        db_table = 'Родители'
        verbose_name = "Родитель"
        verbose_name_plural = "Родители"

    def __str__(self):
        return self.full_name


class PersonalInfo(models.Model):
    id = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=255)
    Gender = models.CharField(max_length=255)
    Birthday = models.DateField()
    Phone_number = models.CharField(max_length=255)
    Address = models.CharField(max_length=255)
    id_parent = models.ForeignKey(Parents, on_delete=models.PROTECT, db_column='id_parent')
    id_group = models.ForeignKey('Group', on_delete=models.PROTECT, db_column='id_group')

    class Meta:
        db_table = 'Личная_информация'
        verbose_name = "Личная информация"
        verbose_name_plural = "Личная информация"

    def __str__(self):
        return self.full_name

    def get_direction_long_name(self):
        return self.id_group.id_direction.Long_name if self.id_group and self.id_group.id_direction else None


class Direction(models.Model):
    id = models.AutoField(primary_key=True)
    Short_name = models.CharField(max_length=255)
    Long_name = models.CharField(max_length=255)

    class Meta:
        db_table = 'Направление'
        verbose_name = "Направление"
        verbose_name_plural = "Направления"

    def __str__(self):
        return self.Long_name


class Teacher(models.Model):
    id = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=255)
    Phone_number = models.CharField(max_length=255)

    class Meta:
        db_table = 'Преподаватели'
        verbose_name = "Преподаватель"
        verbose_name_plural = "Преподаватели"

    def __str__(self):
        return self.full_name


class Department(models.Model):
    id = models.AutoField(primary_key=True)
    id_teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT, db_column='id_teacher')
    Short_name = models.CharField(max_length=255)
    Long_name = models.CharField(max_length=255)
    Decan = models.CharField(max_length=255)
    Phone_number = models.CharField(max_length=255)

    class Meta:
        db_table = 'Кафедра'
        verbose_name = "Кафедра"
        verbose_name_plural = "Кафедры"

    def __str__(self):
        return self.Short_name


class Group(models.Model):
    id = models.AutoField(primary_key=True)
    id_direction = models.ForeignKey(Direction, on_delete=models.PROTECT, db_column='id_napravlenie')
    id_department = models.ForeignKey(Department, on_delete=models.PROTECT, db_column='id_kafedra')
    Year = models.IntegerField()
    Form = models.CharField(max_length=255)
    Degree = models.CharField(max_length=255)

    class Meta:
        db_table = 'Группа'
        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        return f'{self.id_department} {self.Year} ({self.Form} {self.Degree})'


class Subject(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)

    class Meta:
        db_table = 'Предмет'
        verbose_name = "Предмет"
        verbose_name_plural = "Предметы"

    def __str__(self):
        return self.name


class Performance(models.Model):
    id = models.AutoField(primary_key=True)
    id_student = models.ForeignKey(PersonalInfo, on_delete=models.PROTECT, db_column='id_student')
    id_subject = models.ForeignKey(Subject, on_delete=models.PROTECT, db_column='id_Object')
    Exam = models.IntegerField(null=True, blank=True)
    Zachet = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'Успеваемость'
        verbose_name = "Успеваемость"
        verbose_name_plural = "Успеваемость"


class TeacherSubject(models.Model):
    id = models.AutoField(primary_key=True)
    id_teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT, db_column='id_teacher')
    id_subject = models.ForeignKey(Subject, on_delete=models.PROTECT, db_column='id_object')

    class Meta:
        db_table = 'Преподаватель_Предмет'
        verbose_name = "Преподаватель - Предмет"
        verbose_name_plural = "Преподаватели - Предметы"

university/app/templates/add_group.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'form_styles.css' %}" type="text/css">
    <title>Добавить Группу</title>
</head>
<body>
<h1>Добавить Новую Группу</h1>
<div class="form-container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
</div>
</body>
</html>

university/app/templates/add_performance.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'form_styles.css' %}" type="text/css">
    <title>Добавить успеваемость</title>

</head>
<body>
<h1>Добавить успеваемость</h1>
<div class="form-container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
</div>
</body>
</html>

university/app/templates/add_personal_info.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'form_styles.css' %}" type="text/css">
    <title>Добавить личную информацию</title>
</head>
<body>
<h1>Добавить личную информацию</h1>
<div class="form-container">
    <form method="post">
        {% csrf_token %}

        <h2>Информация о родителе</h2>
        {{ form.parent_full_name.label_tag }} {{ form.parent_full_name }}<br>
        {{ form.parent_phone_number.label_tag }} {{ form.parent_phone_number }}<br>

        <h2>Личная информация о студенте</h2>
        {{ form.personal_full_name.label_tag }} {{ form.personal_full_name }}<br>
        {{ form.gender.label_tag }} {{ form.gender }}<br>
        {{ form.birthday.label_tag }} {{ form.birthday }}<br>
        {{ form.phone_number.label_tag }} {{ form.phone_number }}<br>
        {{ form.address.label_tag }} {{ form.address }}<br>
        {{ form.id_group.label_tag }} {{ form.id_group }}<br>

        <button type="submit">Добавить</button>
    </form>
</div>
</body>
</html>

university/app/templates/add_subject.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'form_styles.css' %}" type="text/css">
    <title>Добавить Предмет</title>
</head>
<body>
<h1>Добавить Предмет</h1>
<div class="form-container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
</div>
</body>
</html>

university/app/templates/departments.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Кафедры и Группы</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}" type="text/css">
        <style>
        table {
  display: table;
  width: 80%;
  margin: 0 auto;
  border-collapse: collapse;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);
}
th,td {padding: 15px;
  background-color: rgba(255,255,255,0.2);
  color: #fff;text-align: center;}
h3 {color: #fff;text-align: center;margin-bottom: 20px;}
    </style>
</head>
<body>
<h1>Кафедры и Группы</h1>

{% for department in departments %}
    <h2>{{ department.Long_name }} ({{ department.Short_name }})</h2>
    <p>Декан: {{ department.Decan }}</p>
    <p>Телефон: {{ department.Phone_number }}</p>

    <h3>Группы</h3>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Направление</th>
                <th>Год</th>
                <th>Форма</th>
                <th>Степень</th>
            </tr>
        </thead>
        <tbody>
            {% for group in department.group_set.all %}
                <tr>
                    <td>{{ group.id }}</td>
                    <td>{{ group.id_direction.Long_name }}</td>
                    <td>{{ group.Year }}</td>
                    <td>{{ group.Form }}</td>
                    <td>{{ group.Degree }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">Нет групп для этой кафедры.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endfor %}
</body>
</html>

university/app/templates/group_list.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}" type="text/css">
    <title>Список Групп</title>
        <style>
        body {background:#5f2c82}
        table {
  display: table;
  width: 80%;
  margin: 0 auto;
  border-collapse: collapse;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);
}
th,td {
  padding: 15px;
  background-color: rgba(255,255,255,0.2);
  color: #fff;
  text-align: center;
}
    </style>
</head>
<body>
<h1>Список Групп</h1>
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Кафедра</th>
        <th>Направление</th>
        <th>Год</th>
        <th>Форма</th>
        <th>Степень</th>
    </tr>
    </thead>
    <tbody>
    {% for group in groups %}
    <tr>
        <td>{{ group.id }}</td>
        <td>{{ group.id_department }}</td>
        <td>{{ group.id_direction }}</td>
        <td>{{ group.Year }}</td>
        <td>{{ group.Form }}</td>
        <td>{{ group.Degree }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

university/app/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles.css'%}" type="text/css">
    <title>Курсовая работа</title>
    <style>.button {display: inline-block;padding: 10px 20px;
    margin: 5px;background-color: rgba(255, 255, 255, 0.3);
    color: white;text-align: center;text-decoration: none;
    border: none;border-radius: 5px;
    transition: background-color 0.3s;}
    .button:hover {
    background-color: rgba(255, 255, 255, 0.5);}
    .button-container {display: grid;grid-template-columns: 1fr;
    justify-items: center;margin-top: 20px;
}
    </style>
</head>
<body>
<h1>Студенты университета</h1>
<div>
    <h2>Существующие направления в ВУЗе: </h2>
    <p>Бакалавриат, очная форма обучения: прикладная математика (ПМ), информационные системы и технологии (ИСТ),
        электроэнергетика и электротехника (ЭиЭ), технологические машины и оборудование (ТМО), автоматизация
        технологических процессов и производств (АТПП), химическая технология (ХТ),
        эксплуатация транспортно-технологических машин и комплексов (ЭТТМК). </p>
    <p>Бакалавриат, заочная форма обучения: информационные системы и технологии (ИСТ), электроэнергетика
        и электротехника (ЭиЭ), технологические машины и оборудование (ТМО), автоматизация технологических процессов и
        производств (АТПП),
        химическая технология (ХТ), эксплуатация транспортно-технологических машин и комплексов (ЭТТМК).</p>
    <p>Магистратура, очная форма обучения: информационные системы и технологии (ИСТ), технологические машины и
        оборудование (ТМО),
        автоматизация технологических процессов и производств (АТПП), химическая технология (ХТ).</p>
    <p>Магистратура, очно-заочная форма обучения: информационные системы и технологии (ИСТ), технологические машины и
        оборудование (ТМО),
        автоматизация технологических процессов и производств (АТПП), химическая технология (ХТ).</p>
</div>
<div class="button-container">
    <h2>Навигация</h2>
    <a href="{% url 'admin:index' %}" class="button">Для администратора</a>
    <a href="{% url 'login' %}" class="button">Для преподователей</a>
    <a href="{% url 'login_dec' %}" class="button">Для деканата</a>
    <a href="{% url 'personal_performance' %}" class="button">Проверить успеваемость</a>
</div>
<h2>Количество сессий</h2>
<div class="table-container">
    <table>
        <tr>
            <th>ступень</th>
            <th>форма обучения</th>
            <th>сессий в год</th>
            <th>сессий в общем</th>
        </tr>
        <tr>
            <th>Бакалавриат</th>
            <th>очная форма</th>
            <th>2</th>
            <th>8</th>
        </tr>
        <tr>
            <th>Бакалавриат</th>
            <th>заочная форма</th>
            <th>3</th>
            <th>15</th>
        </tr>
        <tr>
            <th>Магистратура</th>
            <th>очная форма</th>
            <th>2</th>
            <th>4</th>
        </tr>
        <tr>
            <th>Магистратура</th>
            <th>очно-заочная</th>
            <th>2</th>
            <th>6</th>
        </tr>
    </table>
</div>
</body>
</html>

university/app/templates/performance.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
     <link rel="stylesheet" href="{% static 'styles.css'%}" type="text/css">
    <title>Успеваемость студентов</title>
    <style>
        table {
  display: table;
  width: 80%;
  margin: 0 auto;
  border-collapse: collapse;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);
}
th,td {padding: 15px;
  background-color: rgba(255,255,255,0.2);
  color: #fff;text-align: center;}
h3 {color: #fff;text-align: center;margin-bottom: 20px;}
    </style>
</head>
<body>
<h1>Успеваемость студентов</h1>

{% for student in students %}
    <h2>{{ student.full_name }}</h2>
    <p>Пол: {{ student.Gender }}</p>
    <p>Дата рождения: {{ student.Birthday }}</p>
    <p>Телефон: {{ student.Phone_number }}</p>
    <p>Адрес: {{ student.Address }}</p>

    <h3>Успеваемость</h3>
    <table>
        <thead>
            <tr>
                <th>Предмет</th>
                <th>Экзамен</th>
                <th>Зачет</th>
            </tr>
        </thead>
        <tbody>
            {% for performance in student.performance_set.all %}
                <tr>
                    <td>{{ performance.id_subject }}</td>
                    <td>{{ performance.Exam }}</td>
                    <td>{{ performance.Zachet }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">Нет записей об успеваемости для этого студента.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endfor %}
</body>
</html>

university/app/templates/performance_info.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'form_styles.css' %}" type="text/css">
    <style>
        table {
  display: table;
  width: 80%;
  margin: 0 auto;
  border-collapse: collapse;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);
}
th,td {padding: 15px;
  background-color: rgba(255,255,255,0.2);
  color: #fff;text-align: center;}
h3 {color: #fff;text-align: center;margin-bottom: 20px;}
    </style>
    <title>Успеваемость студента</title>
</head>
<body>
<h1>Проверка успеваемости студента</h1>
<div class="form-container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Показать успеваемость</button>
    </form>
</div>
{% if performances %}
<h2>Успеваемость:</h2>
<table>
    <tr>
        <th>Предмет</th>
        <th>Экзамен</th>
        <th>Зачет</th>
    </tr>
    {% for performance in performances %}
    <tr>
        <td>{{ performance.id_subject }}</td>
        <td>{{ performance.Exam }}</td>
        <td>{{ performance.Zachet }}</td>
    </tr>
    {% endfor %}
</table>
{% elif performances is not None %}
<p>Успеваемость не найдена.</p>
{% endif %}
</body>
</html>

university/app/templates/personal_info_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'styles.css' %}" type="text/css">
    <title>Список Личной Информации</title>
            <style>
        body {background:#5f2c82}
        table {
  display: table;
  width: 80%;
  margin: 0 auto;
  border-collapse: collapse;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);
}
th,td {
  padding: 15px;
  background-color: rgba(255,255,255,0.2);
  color: #fff;
  text-align: center;
}
    </style>
</head>
<body>
<h1>Список Личной Информации</h1>
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>ФИО</th>
            <th>Пол</th>
            <th>Дата Рождения</th>
            <th>Телефон</th>
            <th>Адрес</th>
            <th>Родитель</th>
            <th>Группа</th>
        </tr>
    </thead>
    <tbody>
        {% for info in personal_info %}
        <tr>
            <td>{{ info.id }}</td>
            <td>{{ info.full_name }}</td>
            <td>{{ info.Gender }}</td>
            <td>{{ info.Birthday }}</td>
            <td>{{ info.Phone_number }}</td>
            <td>{{ info.Address }}</td>
            <td>{{ info.id_parent }}</td>
            <td>{{ info.id_group }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</body>
</html>

university/app/templates/search_personal_info.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'form_styles.css' %}" type="text/css">
    <title>Поиск личной информации</title>
    <style>
        table {
  display: table;
  width: 80%;
  margin: 0 auto;
  border-collapse: collapse;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);
}
th, td {
  padding: 15px;
  background-color: rgba(255,255,255,0.2);
  color: #fff;
  text-align: center;
}
    </style>
</head>
<body>
<h2>Поиск личной информации</h2>
<div class="form-container">
    <form method="get" action="{% url 'search_personal_info' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Поиск</button>
    </form>
</div>
<h2>Результаты поиска</h2>
<table>
    <tr>
        <th>Полное имя</th>
        <th>Пол</th>
        <th>Дата рождения</th>
        <th>Телефон</th>
        <th>Адрес</th>
    </tr>
    {% for person in results %}
    <tr>
        <td>{{ person.full_name }}</td>
        <td>{{ person.Gender }}</td>
        <td>{{ person.Birthday }}</td>
        <td>{{ person.Phone_number }}</td>
        <td>{{ person.Address }}</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="5">Нет записей, соответствующих вашему запросу.</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

university/app/templates/set_performance.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'form_styles.css' %}" type="text/css">
    <title>Выставление успеваемости</title>
</head>
<body>
<h1>Выставление успеваемости</h1>
<div class="form-container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        {% if students %}
        <h2>Студенты группы {{ group }} по предмету {{ subject }}</h2>
        <input type="hidden" name="subject" value="{{ subject.id }}">
        <input type="hidden" name="group" value="{{ group.id }}">
        {% for student in students %}
        <div>
            <label>{{ student.full_name }}</label>
            <input type="hidden" name="student_ids" value="{{ student.id }}">
            <label for="zachet_{{ student.id }}">Зачет:</label>
            <input type="radio" name="zachet_{{ student.id }}" value="Зачет"> Да
            <input type="radio" name="zachet_{{ student.id }}" value=""> Нет
            <br>
            <label for="exam_{{ student.id }}">Оценка за экзамен:</label>
            <input type="number" name="exam_{{ student.id }}" min="0" max="100" placeholder="Введите оценку">
        </div>
        {% endfor %}
        <button type="submit" name="save_performance">Сохранить успеваемость</button>
        {% else %}
        <button type="submit">Выбрать группу и предмет</button>
        {% endif %}
    </form>
</div>
</body>
</html>

university/app/templates/students.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Группы и студенты</title>
    <link rel="stylesheet" href="{% static 'styles.css'%}" type="text/css">
    <style>
        body {background:#5f2c82}
        table {
  display: table;
  width: 80%;
  margin: 0 auto;
  border-collapse: collapse;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);
}
th,td {
  padding: 15px;
  background-color: rgba(255,255,255,0.2);
  color: #fff;
  text-align: center;
}
    </style>
</head>
<body>
<h1>Группы и студенты</h1>

{% for group in groups %}
    <h2>{{ group }} - {{ group.id_direction.Long_name }}</h2>  <!-- Название группы и направление -->

    <table>
        <thead>
            <tr>
                <th>ФИО</th>
                <th>Пол</th>
                <th>Дата рождения</th>
                <th>Телефон</th>
                <th>Адрес</th>
            </tr>
        </thead>
        <tbody>
            {% for student in group.personalinfo_set.all %}
                <tr>
                    <td>{{ student.full_name }}</td>
                    <td>{{ student.Gender }}</td>
                    <td>{{ student.Birthday }}</td>
                    <td>{{ student.Phone_number }}</td>
                    <td>{{ student.Address }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">Нет студентов в этой группе.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endfor %}
</body>
</html>

university/app/templates/teacher_subject.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Преподаватели и предметы</title>
    <link rel="stylesheet" href="{% static 'styles.css'%}" type="text/css">
    <style>
        body {background:#5f2c82}
        table {
  display: table;
  width: 80%;
  margin: 0 auto;
  border-collapse: collapse;
  overflow: hidden;
  box-shadow: 0 0 20px rgba(0,0,0,0.1);
}
th,td {
  padding: 15px;
  background-color: rgba(255,255,255,0.2);
  color: #fff;
  text-align: center;
}
    </style>
</head>
<body>
<h1>Преподаватели и предметы</h1>

<table>
    <thead>
    <tr>
        <th>Преподаватель</th>
        <th>Предмет</th>
    </tr>
    </thead>
    <tbody>
    {% for teacher_subject in teacher_subjects %}
    <tr>
        <td>{{ teacher_subject.id_teacher.full_name }}</td>  <!-- Имя преподавателя -->
        <td>{{ teacher_subject.id_subject.name }}</td>      <!-- Название предмета -->
    </tr>
    {% empty %}
    <tr>
        <td colspan="2">Нет данных о преподавателях и предметах.</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>